import { InfoPageLayout } from "@/components/InfoPageLayout";
import { createPageMetadata } from "@/lib/siteMetadata";

export const metadata = createPageMetadata(
  "Terms of Use",
  "Terms and acceptable use for the Springfield ID Simpsons character classification app."
);

export default function TermsPage() {
  return (
    <InfoPageLayout title="Terms of Use">
      <p className="text-[var(--text-primary)]">
        By using Springfield ID, you agree to the following terms. This application is intended for
        educational and portfolio demonstration purposes.
      </p>

      <section>
        <h2 className="mb-2 text-base font-semibold text-[var(--text-primary)]">Acceptable use</h2>
        <ul className="list-disc space-y-1 pl-5">
          <li>Upload images you have the right to use for testing and learning.</li>
          <li>Do not upload illegal, harmful, or non-image content.</li>
          <li>Do not attempt to overload, reverse-engineer, or abuse the API.</li>
          <li>Use the classifier for personal, educational, or portfolio purposes only.</li>
        </ul>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-[var(--text-primary)]">Disclaimer</h2>
        <p>
          Predictions are generated by a machine learning model and may be incorrect. Confidence scores
          are estimates, not guarantees. Do not rely on this tool for commercial, legal, or critical
          decisions.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-[var(--text-primary)]">Intellectual property</h2>
        <p>
          <em>The Simpsons</em> and related characters are trademarks of their respective owners.
          This project is a fan-made educational demo and is not affiliated with, endorsed by, or
          sponsored by Fox or Disney. Training images and character names are used solely to
          demonstrate ML classification in an academic/portfolio context.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-[var(--text-primary)]">Service availability</h2>
        <p>
          The app is provided &ldquo;as is&rdquo; without warranties. The service may be unavailable
          during maintenance, Azure outages, or when API credentials are not configured.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-[var(--text-primary)]">Changes</h2>
        <p>
          These terms may be updated as the project evolves. Continued use of the app after changes
          constitutes acceptance of the revised terms.
        </p>
      </section>

      <p className="text-xs">Last updated: June 2026</p>
    </InfoPageLayout>
  );
}
